[buffs]
# This is the option to always show out of dock power for ships when they are docked. Defaults to false
use_out_of_dock_power = true

[ui]
# Set to true to always show the rewards for selected ships/stations
show_cargo_default = false

# These should be self-explanatory
# They control the behavior of the above default option
show_player_cargo = false
show_station_cargo = true
show_hostile_cargo = true
show_armada_cargo = true

# Change 'false' to 'true' from the line below to remove Galaxy Chat from the game
disable_galaxy_chat = false

# Change 'false' to 'true' from the line below to extend the donation slider to max value for next Alliance level
extend_donation_slider = false

# This specifies the types of Banners you DON'T want to see, I think they are relatively self explanatory.
disabled_banner_types = 'Standard,Victory,Defeat'
# This must be a comma seperated list enclosed in single quotes.
# Here is a list of POSSIBLE Banner types
#Standard
#FactionWarning
#FactionLevelUp
#FactionLevelDown
#FactionDiscovered
#IncomingAttack
#IncomingAttackFaction
#FleetBattle
#StationBattle
#StationVictory
#Victory
#Defeat
#StationDefeat
#Event
#ArmadaCreated
#ArmadaCanceled
#ArmadaIncomingAttack
#ArmadaBattleWon
#ArmadaBattleLost
#DiplomacyUpdated
#JoinedTakeover
#CompetitorJoinedTakeover
#AbandonedTerritory
#TakeoverVictory
#TakeoverDefeat

always_skip_reveal_sequence = true
disable_toast_banners = true
stay_in_bundle_after_summary = true

[graphics]
# This is an option that can be enabled to try and keep a more 'useable' UI scale size when resizing the Game Window, defaults to false
adjust_scale_res = false

borderless_fullscreen_f11 = true
free_resize = true

# This controls the zoom speed when using Q/E in System View, defaults to 350
keyboard_zoom_speed = 1000

# This controls how quickly the the momentum falls off when letting go of the mouse, the lower the number the quicker it stops, defaults to 0.8
system_pan_momentum_falloff = 0.8

# This specifies the amount to scale the UI by, 1.0 being default and anything above 1 making it larger than default, defaults to 0.9
ui_scale = 0.7

# This controls the maximum zoom distance in System View, default is 2500.
# If you set this too a very high value the distance at which ship text labels are shown is also increased.
zoom = 2000

# To enable addtional resolution options set this to true.
show_all_resolutions = false

# Set to 0.0 to disable a custom zoom, enter system at specified zoom otherwise, this doesn't work for the first time you view ANY system. But that should be fine
default_system_zoom = 2000.0

# These are used for the F1-F5 zoom hotkeys
system_zoom_preset_1 = 0.0
system_zoom_preset_2 = 0.0
system_zoom_preset_3 = 0.0
system_zoom_preset_4 = 1.0
system_zoom_preset_5 = 2000.0

target_framerate = 60
transition_time = 0.001
vsync = 1

[sync]
token = 'b66e83ca-3df5-472d-aa26-20fbd9e996e5'
url = 'https://spocks.club/sync/ingress/'
resources = true
battlelogs = false
officer = true
missions = false
research = true
tech = false
traits = false
buildings = true
ships = false

[tech]
fix_unity_web_requests = true

[config]
assets_url_override = ''
settings_url = ''

[control]
# If you don't want any hotkeys you can set this to false
hotkeys_enabled = true
hotkeys_extended = true
# If you prefer to use Scopely's hotkeys set this to true
use_scopely_hotkeys = false
